wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 32
LR:
  desc: null
  value: 0.001
DISCOUNT:
  desc: null
  value: 0.9
SYNC_STEPS:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.7.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1714670467.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.7.6
      5: 0.16.6
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
